### ISSUE TITLE
Backend does not issue `quit` command when closing the backend app's window

### ISSUE THREAD

**Issue by JoostHouben** [GediminasMasaitis/CcrlExtensions#3]
Ideally, the backend would issue a `quit` command when shutting down, so that the engine can shutdown gracefully. Failing to do so could leave a zombie process around if the engine doesn't shut down upon a stdin EOF.

@eduherminio just added some code that should do this. However, this code path is not triggered when simply clicking the 'x' button on the backend app's window (in Windows).

**Steps to reproduce**:

 * Start `TlcvExtensionsHost.exe` from Windows explorer by double clicking on the file
 * Click on the 'x' button of the console window that opens
 * Observe that the backend does not issue a `quit` command (e.g., by running your engine under a debugger, adding a breakpoint to the `quit` handler, and noting that the breakpoint is not triggered).

**Partial solution:**

I tried adding the following to Program.cs:
```
AppDomain.CurrentDomain.ProcessExit += (e, a) => StopEngineProcesses(app);
```

With this, the backend now does trigger the `ShutDown` code path on the engine(s) when closing the app, but it seems to lead to some other downstream failures. E.g., if I run it from a console window and close with Ctrl+C instead, this happens:
```
(hit ctrl+c)
[17:22:34 DBG] Euwe-dev << quit
[17:22:34 DBG] Euwe-dev >> info depth 8 seldepth 11 time 657 nodes 68786 nps 104697 hashfull 0 score cp -28 pv f5d3 d1d3 a4a3 b2b3 f8d8 h1d1 e7g5 d3d8 a8d8
[17:22:34 DBG] Euwe-dev >> bestmove f5d3
[17:22:35 DBG] Euwe-dev >> null
[17:22:35 INF] Engine Euwe-dev has exited with exit code 0
Graceful shutdown completed
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Program.<<Main>$>g__StopEngineProcesses|0_6(WebApplication app) in D:\git\TlcvExtensions\src\back\TlcvExtensionsHost\Program.cs:line 56
   at Program.<>c__DisplayClass0_0.<<Main>$>b__4(Object e, EventArgs a) in D:\git\TlcvExtensions\src\back\TlcvExtensionsHost\Program.cs:line 36
```

So it seems this isn't quite the right solution.

**Comment by eduherminio** [comment]
Fixed in https://github.com/GediminasMasaitis/TlcvExtensions/commit/521ba903a3e7bac4b86380bd75e8002748a0bfc (which happened to arrive faster than #6) and improved in the mentioned PR.
Thanks!
